// <auto-generated />
using CQRSMediatRExample.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CQRSMediatRExample.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220511093933_CreateProductTable")]
    partial class CreateProductTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CQRSMediatRExample.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Samsung",
                            Price = 800m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Iphone",
                            Price = 1200m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Xiaomi",
                            Price = 600m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Nokia",
                            Price = 20m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
